"""empty message

Revision ID: 6a68f2b6e75a
Revises: e4aa835ece34
Create Date: 2019-03-02 13:33:37.256561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a68f2b6e75a'
down_revision = 'e4aa835ece34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_update',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_update',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
