"""empty message

Revision ID: 6baedd31adb5
Revises: ab20840f637b
Create Date: 2019-03-01 14:14:04.050334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6baedd31adb5'
down_revision = 'ab20840f637b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('product', 'user_created',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'user_created',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product', 'category',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
