"""empty message

Revision ID: ab20840f637b
Revises: 977e7a6a5814
Create Date: 2019-03-01 10:45:30.731770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab20840f637b'
down_revision = '977e7a6a5814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
