"""empty message

Revision ID: c0e7f698ff99
Revises: ea5b6a651855
Create Date: 2019-03-10 14:30:34.213698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e7f698ff99'
down_revision = 'ea5b6a651855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recovery_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recovery_code')
    # ### end Alembic commands ###
